### ISSUE TITLE
LocalChannel backed by non-ArrayBuf RingBuf

### ISSUE THREAD

**Issue by glebpom** [Matthias247/futures-intrusive#37]
Hi. Thanks for such a great crate! I'm wondering, why `LocalChannel` is explicitly stuck to `ArrayBuf`?

**Comment by Matthias247** [comment]
This is because it's available in the no-std version, which requires a buffer which does not allocate any memory on the heap. If you need a different buffer, you can build it yourself using the `GenericChannel` and freely mix the ring buffer and lock type there.

**Comment by glebpom** [comment]
Thanks. Would it make sense to export `NoopLock` publicly then?
