### ISSUE TITLE
Update `parking_lot` and `lock_api`

### ISSUE THREAD

**Issue by cwfitzgerald** [Matthias247/futures-intrusive#46]
A week or so ago `parking_lot` updated to `0.11`, bringing along with it `lock_api` `0.4.X`. I don't know what would be required to implement this, and due to the increment of `lock_api` would unfortunately have to be a breaking change.

As of right now, as people are starting to upgrade to newer versions of parking_lot, it's also bringing with it the new version of `lock_api`, causing duplicate deps and possible trait mismatches.

If you're willing, I can help make progress on this.

**Comment by Matthias247** [comment]
Should be done #50
