### ISSUE TITLE
Test failures in Fedora packaging

### ISSUE THREAD

**Issue by LecrisUT** [Matthias247/futures-intrusive#68]
The following tests fail when trying to run the tests in Fedora packaging:
```
failures:

---- if_std::mpmc_channel_tests::try_send_unbuffered_panics stdout ----
note: test did not panic as expected
---- local_mpmc_channel_tests::try_send_unbuffered_panics stdout ----
note: test did not panic as expected
```

Any insights on what's going on there?

**Comment by goffrie** [comment]
The panic that is expected is merely a `debug_assert!`. If you aren't building with `-C debug-assertions` then it won't panic.

**Comment by LecrisUT** [comment]
Thanks, I suspect you're referring to:

https://github.com/Matthias247/futures-intrusive/blob/0adfe0e6690d95d8c1d958416955b7a69b203655/tests/mpmc_channel.rs#L280-L285

https://github.com/Matthias247/futures-intrusive/blob/0adfe0e6690d95d8c1d958416955b7a69b203655/src/channel/mpmc.rs#L117-L121
