### ISSUE TITLE
Use alloc instead of std

### ISSUE THREAD

**Issue by leo60228** [Matthias247/futures-intrusive#7]
`Arc` is supported in alloc, not just std.

**Comment by Matthias247** [comment]
Yes, I had that in my mind. However when I wrote the code, `alloc` was not yet stable. I am up for transitioning it and replacing the `std` with an `alloc` feature, but it's not on my high priority list right now. If someone wants to give it a shot please comment here.

**Comment by leo60228** [comment]
I know @roblabla was interested in this.
